// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ljNjI1a6E1UKEDlmIyUoVvmd-OM_-GU',
    appId: '1:284797068484:web:3c0716d39245c8b3f7d591',
    messagingSenderId: '284797068484',
    projectId: 'home-service-3e1d2',
    authDomain: 'home-service-3e1d2.firebaseapp.com',
    storageBucket: 'home-service-3e1d2.firebasestorage.app',
    measurementId: 'G-FGEKGNND5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYg6ZsJfGtsbxQcz4aFXP8bneIwY_AEik',
    appId: '1:284797068484:android:b0b5dd51c68a9710f7d591',
    messagingSenderId: '284797068484',
    projectId: 'home-service-3e1d2',
    storageBucket: 'home-service-3e1d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMeLYJinCpFsGr3RyDtMlHQkWu0S6iZIM',
    appId: '1:284797068484:ios:3f3f747155bddfb6f7d591',
    messagingSenderId: '284797068484',
    projectId: 'home-service-3e1d2',
    storageBucket: 'home-service-3e1d2.firebasestorage.app',
    iosBundleId: 'com.example.workerside',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMeLYJinCpFsGr3RyDtMlHQkWu0S6iZIM',
    appId: '1:284797068484:ios:3f3f747155bddfb6f7d591',
    messagingSenderId: '284797068484',
    projectId: 'home-service-3e1d2',
    storageBucket: 'home-service-3e1d2.firebasestorage.app',
    iosBundleId: 'com.example.workerside',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9ljNjI1a6E1UKEDlmIyUoVvmd-OM_-GU',
    appId: '1:284797068484:web:be107a0b48a25100f7d591',
    messagingSenderId: '284797068484',
    projectId: 'home-service-3e1d2',
    authDomain: 'home-service-3e1d2.firebaseapp.com',
    storageBucket: 'home-service-3e1d2.firebasestorage.app',
    measurementId: 'G-V9510DBSMJ',
  );
}
